# Generated by Django 3.2.6 on 2021-08-14 18:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='guid')),
                ('has_died', models.BooleanField(default=False, verbose_name='has died')),
                ('balance', models.CharField(max_length=255, verbose_name='balance')),
                ('picture', models.URLField(max_length=255, verbose_name='picture')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='age')),
                ('eyeColor', models.CharField(max_length=50, verbose_name='eye color')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20, verbose_name='gender')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('about', models.TextField(verbose_name='about')),
                ('registered', models.DateTimeField(verbose_name='registered')),
                ('greeting', models.TextField(verbose_name='greeting')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoples', to='paranuara.company')),
                ('friend', models.ManyToManyField(related_name='_paranuara_people_friend_+', to='paranuara.People')),
                ('fruit', models.ManyToManyField(related_name='peoples', to='food.Fruit')),
                ('vegetable', models.ManyToManyField(related_name='peoples', to='food.Vegetable')),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
