# Generated by Django 3.2.6 on 2021-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='friend',
            field=models.ManyToManyField(related_name='friends', to='paranuara.People'),
        ),
    ]
