# Generated by Django 3.2.6 on 2021-08-15 09:14

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
